apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: shopcarts-ci-run
  namespace: shopcarts
spec:
  pipelineRef:
    name: shopcarts-ci
  params:
    - name: git-repo
      value: https://github.com/CSCI-GA-2820-FA25-003/shopcarts
    - name: git-ref
      value: feature/lint-task
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/shopcarts/shopcarts:latest
    - name: manifest-dir
      value: k8s
    - name: run-behave
      value: "false"   # Set to "true" to run BDD tests
    - name: base-url
      # Set to Ingress URL for BDD tests (e.g., http://shopcarts.local or http://127.0.0.1:8080)
      # Get Ingress URL: kubectl get ingress -n shopcarts shopcarts-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || kubectl get ingress -n shopcarts shopcarts-ingress -o jsonpath='{.spec.rules[0].host}'
      value: ""  # Default: http://127.0.0.1:8080 (K3D LoadBalancer) or set to actual Ingress URL
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipeline-pvc
  taskRunTemplate:
    serviceAccountName: pipeline
