apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopcarts-ingress
  namespace: shopcarts
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopcarts
            port:
              number: 80

