apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: shopcarts-ci
  namespace: shopcarts
  labels:
    app.kubernetes.io/name: shopcarts
    app.kubernetes.io/component: tekton-pipeline
spec:
  description: >
    CI/CD pipeline for the Shopcarts service modeled after the Orders pipeline:
    clone source, lint, test, deploy manifests, and optionally run Behave tests.
  params:
  - name: git-repo
    type: string
    description: Git repository containing the Shopcarts source.
    default: https://github.com/CSCI-GA-2820-FA25-003/shopcarts
  - name: git-ref
    type: string
    description: Branch, tag, or commit to checkout.
    default: master
  - name: image-name
    type: string
    description: Destination image URL for deployment.
    default: image-registry.openshift-image-registry.svc:5000/shopcarts/shopcarts:latest
  - name: manifest-dir
    type: string
    description: Directory containing Kubernetes manifests.
    default: k8s
  - name: base-url
    type: string
    description: Base URL for Behave tests.
    default: http://shopcarts:8080
  - name: wait-seconds
    type: string
    description: Wait time for Behave steps.
    default: "60"
  - name: driver
    type: string
    description: Web driver to use (chrome or firefox).
    default: chrome
  - name: run-behave
    type: string
    description: Set to "true" to run Behave tests after deployment.
    default: "false"
  workspaces:
  - name: pipeline-workspace
    description: PVC-backed workspace shared across tasks.
  tasks:
  - name: git-clone
    taskRef:
      kind: Task
      name: git-clone
    params:
    - name: URL
      value: $(params.git-repo)
    - name: REVISION
      value: $(params.git-ref)
    - name: SUBMODULES
      value: "true"
    - name: DEPTH
      value: "1"
    - name: DELETE_EXISTING
      value: "true"
    workspaces:
    - name: output
      workspace: pipeline-workspace

  - name: flake8-lint
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: flake8-lint
    workspaces:
    - name: source
      workspace: pipeline-workspace

  - name: pylint
    runAfter:
    - git-clone
    taskRef:
      name: pylint
    workspaces:
    - name: source
      workspace: pipeline-workspace
    params:
    - name: path
      value: .

  - name: pytest
    runAfter:
    - git-clone
    taskRef:
      name: pytest-env
    workspaces:
    - name: source
      workspace: pipeline-workspace

  - name: unit-test
    runAfter:
    - git-clone
    taskRef:
      name: unit-test
    workspaces:
    - name: source
      workspace: pipeline-workspace

  - name: deploy-image
    runAfter:
    - pytest
    - flake8-lint
    - pylint
    - unit-test
    taskRef:
      name: deploy-image
    params:
    - name: image-name
      value: $(params.image-name)
    - name: manifest-dir
      value: $(params.manifest-dir)
    workspaces:
    - name: source
      workspace: pipeline-workspace

  - name: apply-manifests
    runAfter:
    - deploy-image
    taskRef:
      name: apply-manifests
    params:
    - name: manifest-dir
      value: $(params.manifest-dir)
    workspaces:
    - name: source
      workspace: pipeline-workspace

  - name: behave
    runAfter:
    - apply-manifests
    when:
    - input: $(params.run-behave)
      operator: in
      values: ["true"]
    taskRef:
      name: behave
    params:
    - name: base-url
      value: $(params.base-url)
    - name: wait-seconds
      value: $(params.wait-seconds)
    - name: driver
      value: $(params.driver)
    workspaces:
    - name: source
      workspace: pipeline-workspace
