apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: shopcarts-pipeline-template
  namespace: shopcarts
  labels:
    app.kubernetes.io/name: shopcarts
    app.kubernetes.io/component: tekton-trigger
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: Git commit SHA
    - name: git-ref
      description: Git branch/tag reference
    - name: repository-name
      description: Repository full name (owner/repo)
    - name: commit-author
      description: Commit author name
    - name: commit-message
      description: Commit message
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: shopcarts-ci-run-
        namespace: shopcarts
        labels:
          app.kubernetes.io/name: shopcarts
          app.kubernetes.io/component: tekton-pipelinerun
          triggers.tekton.dev/trigger: shopcarts-github-trigger
          triggers.tekton.dev/eventlistener: shopcarts-listener
        annotations:
          triggers.tekton.dev/trigger: shopcarts-github-trigger
          triggers.tekton.dev/eventlistener: shopcarts-listener
      spec:
        pipelineRef:
          name: shopcarts-ci
        params:
          - name: git-repo
            value: $(tt.params.git-url)
          - name: git-ref
            # 從 refs/heads/master 提取 master，或使用完整 ref
            value: $(tt.params.git-ref)
          - name: image-name
            value: image-registry.openshift-image-registry.svc:5000/shopcarts/shopcarts:latest
          - name: manifest-dir
            value: k8s
          - name: run-behave
            value: "false"
          - name: base-url
            value: http://127.0.0.1:8080
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipeline-pvc
        taskRunTemplate:
          serviceAccountName: pipeline

