apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: shopcarts-github-binding
  namespace: shopcarts
  labels:
    app.kubernetes.io/name: shopcarts
    app.kubernetes.io/component: tekton-trigger
spec:
  params:
    # 從 GitHub webhook payload 提取 git repository URL
    # GitHub webhook 的 repository.clone_url 或 repository.html_url
    - name: git-url
      value: $(body.repository.clone_url)
    # 從 GitHub webhook payload 提取 commit SHA
    # GitHub push event 的 'after' 欄位包含新的 commit SHA
    - name: git-revision
      value: $(body.after)
    # 提取分支名稱（例如 refs/heads/master -> master）
    - name: git-ref
      value: $(body.ref)
    # 提取 repository 完整名稱（例如 owner/repo）
    - name: repository-name
      value: $(body.repository.full_name)
    # 提取 commit 作者
    - name: commit-author
      value: $(body.head_commit.author.name)
    # 提取 commit 訊息
    - name: commit-message
      value: $(body.head_commit.message)

